name: firemarkdown
version: 0.0.1
description: mini parser
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  miniparser:
    git:
      url:
        https://github.com/firefirestyle/dart.miniparser.git
dev_dependencies:
  test: any
